from functools import cached_property
from html.parser import HTMLParser
from typing import Literal, Type
from krysalid.managers import Manager
from krysalid.compiler import Compiler

 
class Algorithm(HTMLParser):    
    def __init__(self, **kwargs) -> None: ...


class HTMLPageParser:
    algorithm_class: Type[Algorithm] = ...
    compiler_class: Type[Compiler] = ...
    objects: Manager = ...
    cached_page: str = Literal['']
    algorithm: Algorithm = ...
    compiler: Compiler = ...
    encoding: str = ...

    def __init__(self, html: str = None, encoding: str = Literal['utf-8'], **kwargs): ...
    def __repr__(self) -> str: ...    
    @property
    def has_content(self) -> bool: ...    
    @cached_property
    def get_result_cache(self) -> list: ...    
    @classmethod
    def from_file(cls, path: str, encoding: str = Literal['utf-8']) -> HTMLPageParser: ...
    def parse_page(self) -> None: ...
