from typing import Callable, Optional

from krysalid.parser import HTMLPageParser
from krysalid.queryset import QuerySet

class Manager:
    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...
    def __get__(self, instance: Callable[[HTMLPageParser]], cls: Optional[HTMLPageParser] = ...) -> Manager: ...
    @property
    def html(self) -> None: ...
    @property
    def head(self) -> None: ...
    @property
    def body(self) -> None: ...
    def filter(self) -> None: ...
    def find(self, name: str=..., attrs: dict={}) -> str: ...
    def find_all(self, name: str = ..., attrs: dict = {}) -> QuerySet: ...
