from typing import Any, Generator, Iterator, Literal, Optional, Tuple, Type, TypeVar, Union

from krysalid import queryset
from krysalid.compiler import Compiler
from krysalid.html_tags import Comment, ElementData, NewLine, Tag

_ItemsIterable = TypeVar('_ItemsIterable', bound=queryset.ItemsIterable)


class ItemsIterable:
    queryset: Type[queryset.QuerySet] = ...
    raw_data: list = ...
    def __init__(self, queryset: queryset.QuerySet) -> None: ...
    def __iter__(self) -> Generator: ...


class QuerySet:
    iterable_class: _ItemsIterable = ...
    compiler: Compiler = ...
    result_cache: list[tuple] = ...
    query: dict = ...
    def __init__(self, compiler: Compiler = Optional[None]) -> None: ...
    def __repr__(self) -> str: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator: ...
    def __getitem__(self, index: int) -> Union[Tag, ElementData, NewLine, Comment]: ...
    def __eq__(self, obj: Any) -> bool: ...
    def __and__(self, obj: Any): ...
    def __or__(self, obj: Any): ...
    def __bool__(self) -> bool: ...
    @classmethod
    def clone(cls, compiler: Compiler) -> queryset.QuerySet: ...
    def fetch_all(self) -> None: ...
    def first(self) -> Union[Tag, ElementData, NewLine, Comment]: ...
    def last(self) -> Union[Tag, ElementData, NewLine, Comment]: ...
    def count(self) -> int: ...
    def filter(self, *args, **kwargs) -> queryset.QuerySet: ...
    def find(self, name: str = Optional[None], attrs: dict = Optional[dict]): ...
    def get_text(self, seperator = Optional[None], clean = Optional[True]) -> str: ...
    def find_all(self, name: str = Optional[None], attrs: dict = Optional[dict]) -> queryset.QuerySet: ...
    def distinct(self) -> queryset.QuerySet: ...
    def exclude(self, tag: str, attrs: dict = Optional[dict]) -> queryset.QuerySet: ...
    def union(self, *querysets) -> queryset.QuerySet: ...
    def difference(self, *queryets) -> queryset.QuerySet: ...
    def exists(self) -> bool: ...
    def contains(self, name: str = Optional[None]) -> bool: ...
    def explain(self) -> str: ...
    def update_attribute(self, name: str, attr: str, value: str): ...


class RawQueryset(QuerySet):
    raw_data: list = ...
    def __init__(self, compiler: Compiler, data: list[tuple]) -> None: ...
    @classmethod
    def clone(cls, compiler: Compiler, data: list[Tuple]) -> RawQueryset : ...
    